#ifndef FINGERPRINT_H
#define FINGERPRINT_H

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operation completed successfully.
 */
#define FP_OK 0

/**
 * No supported fingerprint device was found on the USB bus.
 */
#define FP_ERR_DEVICE_NOT_FOUND -1

/**
 * A USB I/O error occurred during communication with the device.
 */
#define FP_ERR_USB_IO -2

/**
 * The operation timed out (e.g. waiting for finger presence).
 */
#define FP_ERR_TIMEOUT -3

/**
 * No finger was detected on the sensor within the timeout window.
 */
#define FP_ERR_NO_FINGER -4

/**
 * The captured image failed validation (wrong size or corrupted).
 */
#define FP_ERR_IMAGE_INVALID -5

/**
 * Template extraction from the captured image failed.
 */
#define FP_ERR_EXTRACT_FAIL -6

/**
 * A required pointer argument was null.
 */
#define FP_ERR_NULL_PTR -7

/**
 * A Rust panic was caught at the FFI boundary.
 */
#define FP_ERR_PANIC -99

#define NOT_PRESENT 1

/**
 * Width of the captured image in pixels.
 */
#define IMAGE_WIDTH 384

/**
 * Height of the captured image in pixels.
 */
#define IMAGE_HEIGHT 289

/**
 * Expected pixel count for a valid, deframed image.
 */
#define IMAGE_SIZE (IMAGE_WIDTH * IMAGE_HEIGHT)

/**
 * Length of the `uru4k_image` header in bytes.
 *
 * Layout (from libfprint):
 * ```text
 *   [0..4]   unknown
 *   [4..6]   num_lines (u16 LE)
 *   [6]      key_number (u8)
 *   [7..16]  unknown
 *   [16..46] block_info (15 × 2 bytes: flags + num_lines)
 *   [46..64] unknown
 * ```
 */
#define IMAGE_HEADER_LEN 64

#define CHANGE_KEY 128

#define NO_KEY_UPDATE 4

#define ENCRYPTED 2

/**
 * Opaque handle to an opened fingerprint scanner.
 *
 * Constructed by [`open()`] and destroyed by [`close()`].  Not
 * `Send` or `Sync` — callers must serialise access.
 */
typedef struct FpDevice FpDevice;

/**
 * Open the first available U.are.U 4500 scanner.
 *
 * Returns an opaque device handle on success, or `NULL` on failure.
 * The handle is **not** thread-safe.
 */
FpDevice *fp_open(void);

/**
 * Capture a fingerprint and extract a template.
 *
 * Blocks until a finger is placed on the sensor (or `timeout_ms`
 * expires), captures the image, and writes the template to
 * `*template_out` / `*len_out`.
 *
 * On success: returns `FP_OK`, `*template_out` points to a
 * heap-allocated buffer, `*len_out` is its length.  Caller **must**
 * call `fp_free(*template_out, *len_out)`.
 *
 * On failure: returns a non-zero error code.  `*template_out` and
 * `*len_out` are set to `NULL` / `0`.
 */
int32_t fp_scan_and_extract(FpDevice *dev,
                            uint32_t timeoutMs,
                            uint8_t **templateOut,
                            uintptr_t *lenOut);

/**
 * Compare two templates and output a similarity score.
 *
 * Does **not** require a device handle.  `score_out` is written on
 * success (range `[0.0, 1.0]`).
 *
 * Returns `FP_OK` on success, non-zero on failure.
 */
int32_t fp_verify(const uint8_t *tmplA,
                  uintptr_t lenA,
                  const uint8_t *tmplB,
                  uintptr_t lenB,
                  double *scoreOut);

/**
 * Free a template buffer previously returned by `fp_scan_and_extract`.
 *
 * # Safety
 *
 * `ptr` must have been returned by a successful call to
 * `fp_scan_and_extract`.  Passing any other pointer is UB.
 * Calling `fp_free` twice on the same pointer is UB.
 */
void fp_free(uint8_t *ptr, uintptr_t len);

/**
 * Close the device handle returned by `fp_open`.
 *
 * After this call the pointer is invalid.
 */
void fp_close(FpDevice *dev);

/**
 * Return a static, null-terminated human-readable string for an error code.
 *
 * The returned pointer is valid for the lifetime of the process.
 * Returns `"unknown error"` for unrecognised codes.
 */
const char *fp_strerror(int32_t code);

#endif  /* FINGERPRINT_H */
