#ifndef FINGERPRINT_H
#define FINGERPRINT_H

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>







/**
 * Operation completed successfully.
 */
#define FP_OK 0

/**
 * No supported fingerprint device was found on the USB bus.
 */
#define FP_ERR_DEVICE_NOT_FOUND -1

/**
 * A USB I/O error occurred during communication with the device.
 */
#define FP_ERR_USB_IO -2

/**
 * The operation timed out (e.g. waiting for finger presence).
 */
#define FP_ERR_TIMEOUT -3

/**
 * No finger was detected on the sensor within the timeout window.
 */
#define FP_ERR_NO_FINGER -4

/**
 * The captured image failed validation (wrong size or corrupted).
 */
#define FP_ERR_IMAGE_INVALID -5

/**
 * Template extraction from the captured image failed.
 */
#define FP_ERR_EXTRACT_FAIL -6

/**
 * A required pointer argument was null.
 */
#define FP_ERR_NULL_PTR -7

/**
 * A Rust panic was caught at the FFI boundary.
 */
#define FP_ERR_PANIC -99

#define NOT_PRESENT 1

/**
 * Expected pixel count for a valid, deframed image.
 */
#define IMAGE_SIZE (IMAGE_WIDTH * IMAGE_HEIGHT)

#define CHANGE_KEY 128

#define NO_KEY_UPDATE 4

#define ENCRYPTED 2

/**
 * Opaque opened scanner handle.
 *
 * The active backend is hidden behind an enum so the public C ABI
 * does not change as new drivers are added.
 */
typedef struct FpDevice FpDevice;

/**
 * Callback signature used by [`fp_scan_continuous`].
 *
 * The callback receives a borrowed template pointer valid only for
 * the duration of the callback invocation. Return `true` to keep
 * scanning, or `false` to stop.
 */
typedef bool (*FpTemplateCallback)(const uint8_t*, uintptr_t, void*);

/**
 * Open the first available supported scanner.
 *
 * Returns an opaque device handle on success, or `NULL` on failure.
 * The handle is **not** thread-safe.
 */
FpDevice *fp_open(void);

/**
 * Capture a fingerprint and extract a template.
 *
 * Blocks until a finger is placed on the sensor (or `timeout_ms`
 * expires), captures the image, and writes the template to
 * `*template_out` / `*len_out`.
 *
 * On success: returns `FP_OK`, `*template_out` points to a
 * heap-allocated buffer, `*len_out` is its length.  Caller **must**
 * call `fp_free(*template_out, *len_out)`.
 *
 * On failure: returns a non-zero error code.  `*template_out` and
 * `*len_out` are set to `NULL` / `0`.
 */
int32_t fp_scan_and_extract(FpDevice *dev,
                            uint32_t timeoutMs,
                            uint8_t **templateOut,
                            uintptr_t *lenOut);

/**
 * Capture multiple scans of the same finger and combine them into one
 * enrollment template package.
 *
 * This function performs enrollment-style multi-capture:
 * - captures `scan_count` templates from the same finger
 * - retries each slot up to `max_attempts_per_scan` on recoverable capture failures
 * - combines all captured templates into one opaque multi-view template
 *
 * `scan_count` should typically be `6`.
 *
 * On success: returns `FP_OK`, sets `*template_out` and `*len_out`.
 * Caller must free with `fp_free`.
 */
int32_t fp_enroll_multi(FpDevice *dev,
                        uint32_t timeoutMs,
                        uint32_t scanCount,
                        uint32_t maxAttemptsPerScan,
                        uint8_t **templateOut,
                        uintptr_t *lenOut);

/**
 * Compare two templates and output a similarity score.
 *
 * Does **not** require a device handle.  `score_out` is written on
 * success (range `[0.0, 1.0]`).
 *
 * Returns `FP_OK` on success, non-zero on failure.
 */
int32_t fp_verify(const uint8_t *tmplA,
                  uintptr_t lenA,
                  const uint8_t *tmplB,
                  uintptr_t lenB,
                  double *scoreOut);

/**
 * Identify the best match for one probe template against a candidate set.
 *
 * This is a 1:N helper for backend/app code that already has a table of
 * stored enrollment templates (for example, users in an access-control app).
 *
 * Inputs:
 * - `probe_tmpl` / `probe_len`: the freshly scanned template
 * - `candidates`: array of candidate template pointers
 * - `candidate_lens`: array of candidate template lengths
 * - `candidate_count`: number of entries in both arrays
 * - `threshold`: match threshold in `[0.0, 1.0]`
 *
 * Outputs:
 * - `*match_index_out`: index of best candidate if score >= threshold, else `SIZE_MAX`
 * - `*match_score_out`: best score found across all candidates
 *
 * Returns `FP_OK` on success, non-zero on failure.
 */
int32_t fp_identify(const uint8_t *probeTmpl,
                    uintptr_t probeLen,
                    const uint8_t *const *candidates,
                    const uintptr_t *candidateLens,
                    uintptr_t candidateCount,
                    double threshold,
                    uintptr_t *matchIndexOut,
                    double *matchScoreOut);

/**
 * Keep scanner active and stream templates via callback.
 *
 * This helper is intended for attendance/check-in workflows where
 * the scanner stays open and many users scan one after another.
 *
 * - `max_scans = 0` means run until callback returns `false`.
 * - Recoverable capture failures are ignored and scanning continues.
 * - Callback receives a borrowed template pointer that is only valid
 *   during callback execution; copy it if needed.
 */
int32_t fp_scan_continuous(FpDevice *dev,
                           uint32_t timeoutMs,
                           uint32_t maxScans,
                           FpTemplateCallback callback,
                           void *userData);

/**
 * Free a template buffer previously returned by `fp_scan_and_extract`
 * or `fp_enroll_multi`.
 *
 * # Safety
 *
 * `ptr` must have been returned by a successful call to
 * `fp_scan_and_extract` or `fp_enroll_multi`.  Passing any other pointer is UB.
 * Calling `fp_free` twice on the same pointer is UB.
 */
void fp_free(uint8_t *ptr, uintptr_t len);

/**
 * Close the device handle returned by `fp_open`.
 *
 * After this call the pointer is invalid.
 */
void fp_close(FpDevice *dev);

/**
 * Return a static, null-terminated human-readable string for an error code.
 *
 * The returned pointer is valid for the lifetime of the process.
 * Returns `"unknown error"` for unrecognised codes.
 */
const char *fp_strerror(int32_t code);

#endif  /* FINGERPRINT_H */
